package com.example.demo;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.ArrayList;
import java.util.List;

@Configuration
class DatabasePopulator {
  @Bean
  Database database() {
    return new Database()
        .setAnimal(animals())
        .setNumber(numbers())
        .setFood(foods())
        .setJob(jobs())
        .setEmotion(emotions())
        .setPoliteness(politeness())
        .setCountry(country())
        .setPlace(place())
        .setClothing(clothing())
        .setColor(color())
        .setFamily(family())
        .setPointer(pointer())
        .setThingy(thingy())
        .setAction(action())
        .setActionable(actionable())
        .setDaytime(daytime())
        .setSport(sport())
        .setGenre(genre())
        .setName(name())
        .setCounting(counting())
        .setPronounHell(pronounHell())
        .setAlignment(alignment())
        .setEverythingElse(random());
  }

  private List<DatabaseRecord> pronounHell() {
    return listOf(
        new DatabaseRecord(expl("I", "male"), "ぼく", "僕"),
        new DatabaseRecord(expl("I", "female"), "わたし", "私"),
        new DatabaseRecord("you", "あなた"),
        new DatabaseRecord("he", "かれ", "彼"),
        new DatabaseRecord("they", "かれら", "彼ら"),
        new DatabaseRecord("she", expl("かのじょ", "pronoun")),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> counting() {
    return listOf(
        new DatabaseRecord("one person", "ひとり", "一人"),
        new DatabaseRecord("two persons", "ふたり", "二人"),
        new DatabaseRecord("one pie", "ひとつ", "一つ"),
        new DatabaseRecord("two pies", "ふたつ", "二つ"),
        new DatabaseRecord("three pies", "みっつ", "三つ"),
        new DatabaseRecord("four pies", "よっつ", "四つ"),
        new DatabaseRecord("five pies", "いつつ", "五つ"),
        new DatabaseRecord("six pies", "むっつ"),
        new DatabaseRecord("seven pies", "ななつ"),
        new DatabaseRecord("eight pies", "やっつ"),
        new DatabaseRecord("nine pies", "ここのつ"),
        new DatabaseRecord("lot of", "たくさん"),
        new DatabaseRecord("two birds", "にわ", "二羽"),
        new DatabaseRecord("three birds", "さんわ", "三羽"),
        new DatabaseRecord("one egg", "いっこ", "一個"),
        new DatabaseRecord("two eggs", "にこ", "二個"),
        new DatabaseRecord("how many pies", "いくつ"),
        new DatabaseRecord("ten books", "じゅうさつ", "十冊"),
        new DatabaseRecord("six apples", "ろっこ", "六個"),
        new DatabaseRecord("hundred pictures", "ひゃくまい", "百枚"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> name() {
    return listOf(
        new DatabaseRecord("ken", "けん", null),
        new DatabaseRecord("hana", expl("はな", "名"), null),
        new DatabaseRecord("naomi", "なおみ", null),
        new DatabaseRecord("daniel", "ダニエル", null),
        new DatabaseRecord("andrew", "アンドリュ", null),
        new DatabaseRecord("erika", "エリカ", null),
        new DatabaseRecord(expl("smith", "名"), "スミス"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> random() {
    return listOf(
        new DatabaseRecord("no", "いいえ", null),
        new DatabaseRecord("yes", "はい", null),
        new DatabaseRecord("um", "ええと", null),
        new DatabaseRecord("oh", "あ", null),
        new DatabaseRecord("okay then", "じゃあ", null),
        new DatabaseRecord("make sure", "ちゃんと", null),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> action() {
    return listOf(
        new DatabaseRecord("watch", "みます", "見ます"),
        new DatabaseRecord("do", "します"),
        new DatabaseRecord("read", "よみます", "読みます"),
        new DatabaseRecord("listen", expl("ききます", "おんがく"), "聞きます"),
        new DatabaseRecord("ask", expl("ききます", "しつもん"), "聞きます"),
        new DatabaseRecord("eat", "たべます", "食べる"),
        new DatabaseRecord("drink", "のみます", "飲む"),
        new DatabaseRecord("swim", "およぎます", "泳ぎます"),
        new DatabaseRecord("hang out", "あそびます", "遊びます"),
        new DatabaseRecord("buy", "かいます", "買います"),
        new DatabaseRecord("go out", "でかけます", null),
        new DatabaseRecord("talk", "はなします", "話します"),
        new DatabaseRecord(expl("have", "inanimate"), "あります", null),
        new DatabaseRecord(expl("have", "living thing"), "います", null),
        new DatabaseRecord("get up", "おきます", null),
        new DatabaseRecord("run", "はしります", "走ります"),
        new DatabaseRecord("named", "いいます", null),
        new DatabaseRecord(expl("take", "a picture"), "とります", "撮ります"),
        new DatabaseRecord("make", "つくります", "作ります"),
        new DatabaseRecord("sleep", "ねます", "寝ます"),
        new DatabaseRecord(expl("take", "a shower"), "あびます", "浴びます"),
        new DatabaseRecord("live", "すんでいます", "住んでいます"),
        new DatabaseRecord(expl("move", "house"), "ひっこします", null),
        new DatabaseRecord(expl("go", "away"), "いきます", "行きます"),
        new DatabaseRecord(expl("take", "time"), "かかります", null),
        new DatabaseRecord("come", "きます", "来ます"),
        new DatabaseRecord("rest", "やすみます", "休みます"),
        new DatabaseRecord(expl("need", "I need help please"), "おねがいします", null),
        new DatabaseRecord("able", "できます", null),
        new DatabaseRecord("sit", "すわります", "座ります"),
        new DatabaseRecord("meet", "あいます", "会います"),
        new DatabaseRecord("help", "てつだいます", null),
        new DatabaseRecord("return", "かえります", "帰ります"),
        new DatabaseRecord("wait", "まちます"),
        new DatabaseRecord(expl("ride", "train"), "のります"),
        new DatabaseRecord(expl("end", "finishes"), "おわります"),
        new DatabaseRecord("use", "つかいます", "使います"),
        new DatabaseRecord(expl("wear", "upper body"), "きます", "着ます"),
        new DatabaseRecord(expl("wear", "lower body"), "はきます"),
        new DatabaseRecord(expl("wear", "head"), "かぶります", "被ります"),
        new DatabaseRecord("wash", "あらいます", "洗います"),
        new DatabaseRecord("write", "かきます", "書きます"),
        new DatabaseRecord("draw", "かきます", "描きます"),
        new DatabaseRecord("begin", "はじまります"),
        new DatabaseRecord("dance", "おどります"),
        new DatabaseRecord(expl("play", "an instrument"), "ひきます", "弾きます"),
        new DatabaseRecord("sing", "うたいます", "歌います"),
        new DatabaseRecord("be called", "もうします", "申します"),
        new DatabaseRecord("work", "はたらきます", "働きます"),
        new DatabaseRecord(expl("open", "window"), "あけます", "開けます"),
        new DatabaseRecord(expl("close", "window"), "しめます", "閉めます"),
        new DatabaseRecord("stand", "たちます", "立ちます"),
        new DatabaseRecord("turn on", "つけます"),
        new DatabaseRecord("take off", "ぬぎます", "脱ぎます"),
        new DatabaseRecord("walk", "あるきます", "歩きます"),
        new DatabaseRecord("resemble", "にます", "似ます"),
        new DatabaseRecord("learn", "ならいます", "習います"),
        new DatabaseRecord("blow", "ふきます", "吹きます"),
        new DatabaseRecord("fall", "ふります", "降ります"),
        new DatabaseRecord("teach", "おしえます", "教えます"),
        new DatabaseRecord(expl("call", "with a phone"), "かけます"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> actionable() {
    return listOf(
        new DatabaseRecord(expl("game", "video -"), "ゲーム", null),
        new DatabaseRecord("job", "しごと", "仕事"),
        new DatabaseRecord("study", "べんきょう", "勉強"),
        new DatabaseRecord("party", "パーティー", null),
        new DatabaseRecord("shower", "シャワ-", null),
        new DatabaseRecord("like", "すき", "好き"),
        new DatabaseRecord(expl("love", "like a lot"), "だいすき", "だい好き"),
        new DatabaseRecord("photo", "しゃしん", "写真"),
        new DatabaseRecord("gardening", "ガ-デニング", null),
        new DatabaseRecord("shopping", "かいもの", "買い物"),
        new DatabaseRecord("cooking", "りょうり", "料理"),
        new DatabaseRecord("homework", "しゅくだい", null),
        new DatabaseRecord("chore", "かじ", null),
        new DatabaseRecord("look forward to", "たのしみ", null),
        new DatabaseRecord("sightseeing", "かんこう"),
        new DatabaseRecord("exercise", "うんどう"),
        new DatabaseRecord("driving", "うんてん"),
        new DatabaseRecord("translation", "ほんやく"),
        new DatabaseRecord("stroll", "さんぽ", "散歩"),
        new DatabaseRecord("song", "うた", "歌"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> sport() {
    return listOf(
        new DatabaseRecord("yoga", "ヨガ", null),
        new DatabaseRecord("soccer", "サッカー", null),
        new DatabaseRecord("basketball", "バスケットボール", null),
        new DatabaseRecord("baseball", "やきゅう", null),
        new DatabaseRecord("sports", "スポーツ", null),
        new DatabaseRecord("tennis", "テニス", null),
        new DatabaseRecord("judo", "じゅうどう", null),
        new DatabaseRecord("hobby", "しゅみ", null),
        new DatabaseRecord("volleyball", "バレ-ボ-ル", null),
        new DatabaseRecord("karate", "からて", null),
        new DatabaseRecord("stretch", "ストレッチ", null),
        new DatabaseRecord("pro", "プロ"),
        new DatabaseRecord("gym", "ジム"),
        new DatabaseRecord("player", "せんしゅ"),
        new DatabaseRecord("team", "チ-ム"),
        new DatabaseRecord("badminton", "バドミントン"),
        new DatabaseRecord("ballet", "バレイ"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> genre() {
    return listOf(
        new DatabaseRecord("action", "アクション", null),
        new DatabaseRecord("horror", "ホラ-", null),
        new DatabaseRecord("drama", "ドラマ", null),
        new DatabaseRecord("romance", "れんあい", null),
        new DatabaseRecord("comedy", "コメディ", null),
        new DatabaseRecord("fantasy", "ファンタジー", null),
        new DatabaseRecord("mystery", "ミステリ-", null),
        new DatabaseRecord("documentary", "ドキュメンタリ-"),
        new DatabaseRecord("pop", "ポップス"),
        new DatabaseRecord("fiction", "フィクション"),
        new DatabaseRecord("non-fiction", "ノンフィクション"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> thingy() {
    return listOf(
        new DatabaseRecord("anime", "アニメ"),
        new DatabaseRecord("anime music", "アニソン"),
        new DatabaseRecord("book", "ほん", "本"),
        new DatabaseRecord("tv", "テレビ"),
        new DatabaseRecord("movie", "えいが", "映画"),
        new DatabaseRecord("music", "おんがく", "音楽"),
        new DatabaseRecord("magazine", "ざっし", null),
        new DatabaseRecord("manga", "まんが", null),
        new DatabaseRecord("passport", "パスポート"),
        new DatabaseRecord("smartphone", "スマホ"),
        new DatabaseRecord(expl("ticket", "train"), "きっぷ", null),
        new DatabaseRecord("ticket gate", "かいさつ", null),
        new DatabaseRecord("floor", "かい", "階"),
        new DatabaseRecord("first floor", "いっかい", "一階"),
        new DatabaseRecord("second floor", "にかい", "二階"),
        new DatabaseRecord("which floor", "なんかい", "何階"),
        new DatabaseRecord("elevator", "エレベーター"),
        new DatabaseRecord("underground", "ちか"),
        new DatabaseRecord("friend", "ともだち", "友達"),
        new DatabaseRecord("video", "どうが"),
        new DatabaseRecord("storage locker", "コインロッカ-"),
        new DatabaseRecord("vending machine", "じはんき"),
        new DatabaseRecord("exit", "でぐち", null),
        new DatabaseRecord("entrance", "いりぐち", null),
        new DatabaseRecord("cafe", "カフェ", null),
        new DatabaseRecord("stair", "かいだん", null),
        new DatabaseRecord("phone", "でんわ", "電話"),
        new DatabaseRecord("phone number", "でんわばんごう", null),
        new DatabaseRecord("outlet", "コンセント", null),
        new DatabaseRecord("taxi", "タクシ-", null),
        new DatabaseRecord("transfer", "のりかえ", null),
        new DatabaseRecord("trash can", "ゴミばこ", null),
        new DatabaseRecord("platform", "ホ-ム", null),
        new DatabaseRecord("newspaper", "しんぶん", "新聞"),
        new DatabaseRecord("radio", "ラジオ", null),
        new DatabaseRecord("travel", "りょこう", "旅行"),
        new DatabaseRecord("email", "メ-ル", null),
        new DatabaseRecord("apartment", "アパ-ト", null),
        new DatabaseRecord(expl("kitchen", "modern"), "キッチン", null),
        new DatabaseRecord(expl("kitchen", "older"), "だいどころ", "台所"),
        new DatabaseRecord("air conditioner", "エアコン", null),
        new DatabaseRecord("washing machine", "せんたくき", "洗濯機"),
        new DatabaseRecord("laundry", "せんたく", "洗濯"),
        new DatabaseRecord("bookshelf", "ほんだな", "本棚"),
        new DatabaseRecord("shelf", "だな", "棚"),
        new DatabaseRecord("window", "まど", "窓"),
        new DatabaseRecord("bathroom", "トイレ"),
        new DatabaseRecord("house", "いえ", "家"),
        new DatabaseRecord("living room", "リビング", null),
        new DatabaseRecord("bed", "ベッド", null),
        new DatabaseRecord("vacuum cleaner", "そうじき", "掃除機"),
        new DatabaseRecord("cleaning", "そうじ", "掃除"),
        new DatabaseRecord("housework", "いえのそうじ", "家の掃除"),
        new DatabaseRecord("fridge", "れいぞうこ", "冷蔵庫"),
        new DatabaseRecord("desk", "つくえ", "机"),
        new DatabaseRecord("microwave", "でんしレンジ", null),
        new DatabaseRecord("futon", "ふとん", "布団"),
        new DatabaseRecord("chair", "いす", "椅子"),
        new DatabaseRecord("table", "テ-ブル", null),
        new DatabaseRecord("next", "つぎ"),
        new DatabaseRecord(expl("really", "word"), "ほんとう", null),
        new DatabaseRecord("postcard", "ポストカ-ド", null),
        new DatabaseRecord("condition", "ぐあい", null),
        new DatabaseRecord("number", "ばんごう", null),
        new DatabaseRecord("ambulance", "きゅうきゅうしゃ", null),
        new DatabaseRecord("allergy", "アレルギ-", null),
        new DatabaseRecord("mountain", "やま", "山"),
        new DatabaseRecord("flower", expl("はな", "花"), null),
        new DatabaseRecord("medicine", "くすり", null),
        new DatabaseRecord("police", "けいさつ", null),
        new DatabaseRecord("hospital", "びょういん", null),
        new DatabaseRecord("weather", "てんき", "天気"),
        new DatabaseRecord("rain", "あめ", "雨"),
        new DatabaseRecord("beach", "うみ"),
        new DatabaseRecord("sunny", "はれ", "晴れ"),
        new DatabaseRecord("sunny day", "はれのひ"),
        new DatabaseRecord("snow", "ゆき", "雪"),
        new DatabaseRecord("snowy day", "ゆきのひ"),
        new DatabaseRecord("pool", "プ-ル"),
        new DatabaseRecord("firework", "はなび"),
        new DatabaseRecord("break", "やすみ", "休み"),
        new DatabaseRecord("cloud", "くも", "雲"),
        new DatabaseRecord("cloudy", "くもり", "曇り"),
        new DatabaseRecord("cloudy day", "くもりのひ"),
        new DatabaseRecord("concert", "コンサ-ト"),
        new DatabaseRecord("painting", "え", "絵"),
        new DatabaseRecord(expl("ticket", "airplane"), "チケット", null),
        new DatabaseRecord("airplane", "ひこうき", "飛行機"),
        new DatabaseRecord("train", "でんしゃ", "電車"),
        new DatabaseRecord("bullet train", "しんかんせん"),
        new DatabaseRecord("bus", "バス"),
        new DatabaseRecord("suitcase", "スーツケース"),
        new DatabaseRecord(expl("bath", "formal"), "おふろ", null),
        new DatabaseRecord(expl("bath", "informal"), "ふろ", "風呂"),
        new DatabaseRecord("rest day", "やすみのひ", "休みの日"),
        new DatabaseRecord("stuff", "もの"),
        new DatabaseRecord("seat", "せき"),
        new DatabaseRecord("class", "じゅぎょう"),
        new DatabaseRecord("project", "プロジェクト"),
        new DatabaseRecord("deadline", "しめきり"),
        new DatabaseRecord("early", "はやく"),
        new DatabaseRecord("question", "しつもん"),
        new DatabaseRecord("test", "テスト"),
        new DatabaseRecord("classroom", "きょうしつ"),
        new DatabaseRecord("together", "いっしょ", "一緒"),
        new DatabaseRecord("free", "ひま"),
        new DatabaseRecord("event", "イベント"),
        new DatabaseRecord("entrance fee", "にゅうじょうりょう"),
        new DatabaseRecord("roller coaster", "ジェットコースター"),
        new DatabaseRecord("mascot", "キャラクタ-"),
        new DatabaseRecord("face", "かお"),
        new DatabaseRecord("flavor", "あじ"),
        new DatabaseRecord("camera", "カメラ"),
        new DatabaseRecord("dictionary", "じしょ"),
        new DatabaseRecord("poster", "ポスタ-"),
        new DatabaseRecord("card game", "カ-ドゲ-ム"),
        new DatabaseRecord("puzzle", "パズル"),
        new DatabaseRecord("band", "バンド"),
        new DatabaseRecord("album", "アルバム"),
        new DatabaseRecord(expl("really", "don't really read"), "あまり"),
        new DatabaseRecord("story", "はなし", "話"),
        new DatabaseRecord("section", "コ-ナ-"),
        new DatabaseRecord("sale", "セ-ル"),
        new DatabaseRecord("size", "サイズ"),
        new DatabaseRecord("show", "ショ-"),
        new DatabaseRecord("go-kart", "ゴ-カ-ト"),
        new DatabaseRecord("attraction", "アトラクション"),
        new DatabaseRecord("theme park", "ゆうえんち"),
        new DatabaseRecord("museum", "はくぶつかん"),
        new DatabaseRecord("post", "きじ"),
        new DatabaseRecord("fashion", "ファッション"),
        new DatabaseRecord("blog", "ブログ"),
        new DatabaseRecord("hiragana", "ひらがな"),
        new DatabaseRecord("kanji", "かんじ"),
        new DatabaseRecord("guitar", "ギター"),
        new DatabaseRecord("instrument", "がっき"),
        new DatabaseRecord("piano", "ピアノ"),
        new DatabaseRecord("practice", "れんしゅう", "練習"),
        new DatabaseRecord(expl("game", "match"), "しあい"),
        new DatabaseRecord("last", "さいご"),
        new DatabaseRecord("karaoke", "カラオケ"),
        new DatabaseRecord("presentation", "プレゼン"),
        new DatabaseRecord("computer", "パソコン"),
        new DatabaseRecord("lunch break", "ひるやすみ", "ひる休み"),
        new DatabaseRecord("client", "クライアント"),
        new DatabaseRecord(expl("training", "job-related"), "トレーニング"),
        new DatabaseRecord("printer", "プリンター"),
        new DatabaseRecord("meeting", "ミーティング"),
        new DatabaseRecord("front desk", "うけつけ"),
        new DatabaseRecord("which school year", "なんねんせい", "何年生"),
        new DatabaseRecord("bedroom", "しんしつ", "寝室"),
        new DatabaseRecord("sofa", "ソファー"),
        new DatabaseRecord("room", "へや", "部屋"),
        new DatabaseRecord("difference", "ちがい", "違い"),
        new DatabaseRecord("foreigner", "がいこくじん", "外国人"),
        new DatabaseRecord("foreign exchange student", "りゅうがくせい", "留学生"),
        new DatabaseRecord("mood", "ちょうし", "調子"),
        new DatabaseRecord("performance", "パフォーマンス"),
        new DatabaseRecord("lesson", "レッスン"),
        new DatabaseRecord("a little bit", "ちょっと"),
        new DatabaseRecord("mirror", "かがみ", "鏡"),
        new DatabaseRecord("electricity", "でんき", "電気"),
        new DatabaseRecord("very", "とても"),
        new DatabaseRecord("a bit", "すこし"),
        new DatabaseRecord("color", "いろ", "色"),
        new DatabaseRecord("bicycle", "じてんしゃ", "自転車"),
        new DatabaseRecord("car", "くるま", "車"),
        new DatabaseRecord("being home", "ざいたく", "在宅"),
        new DatabaseRecord("letter", "てがみ", "手紙"),
        new DatabaseRecord("wind", "かぜ", "風"),
        new DatabaseRecord("sky", "そら", "空"),
        new DatabaseRecord("beverage", "のみもの", "飲み物"),
        new DatabaseRecord("fruit", "くだもの", "果物"),
        new DatabaseRecord("sugar", "さとう", "砂糖"),
        new DatabaseRecord("alcohol", "おさけ", "お酒"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> pointer() {
    return listOf(
        new DatabaseRecord("this one", "これ", null),
        new DatabaseRecord("that one", "それ", null),
        new DatabaseRecord("which one", "どれ", null),
        new DatabaseRecord("this", "この", null),
        new DatabaseRecord("that", "その", null),
        new DatabaseRecord("here", "ここ", null),
        new DatabaseRecord("there", "そこ", null),
        new DatabaseRecord("where", "どこ", null),
        new DatabaseRecord("how", "どう", null),
        new DatabaseRecord("these ones", "これら", null),
        new DatabaseRecord("those ones", "それら", null),
        new DatabaseRecord("that over there", "あの", null),
        new DatabaseRecord("that one over there", "あれ", null),
        new DatabaseRecord("over there", "あそこ", null),
        new DatabaseRecord("nearby", "ちかく", null),
        new DatabaseRecord("what kind of", "どんな", null),
        new DatabaseRecord("this way", "こちら", null),
        new DatabaseRecord(expl("when", "what time"), "いつ", null),
        new DatabaseRecord("how long", expl("どの", "時間"), null),
        new DatabaseRecord("which", expl("どの", "物"), null),
        new DatabaseRecord("and then", "そして", null),
        new DatabaseRecord("who", "だれ", "誰"),
        new DatabaseRecord("after", "あと", null),
        new DatabaseRecord("from then on", "それから", null),
        new DatabaseRecord("but", "でも"),
        new DatabaseRecord("more", "もっと"),
        new DatabaseRecord("until", "まで"),
        new DatabaseRecord(expl("from", "time"), "から"),
        new DatabaseRecord("well then", "では"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> family() {
    return listOf(
        new DatabaseRecord("younger sister", "いもうと", "妹"),
        new DatabaseRecord(expl("older sister", "own"), "あね", "姉"),
        new DatabaseRecord(expl("older sister", "other's"), "おねえ"),
        new DatabaseRecord("younger brother", "おとうと", "弟"),
        new DatabaseRecord("older brother", "あに", "兄"),
        new DatabaseRecord(expl("older brother", "other's"), "おにい", "お兄"),
        new DatabaseRecord(expl("mother", "own"), "はは", "母"),
        new DatabaseRecord(expl("mother", "other's"), "おかあ", "お母"),
        new DatabaseRecord(expl("father", "own"), "ちち", "父"),
        new DatabaseRecord(expl("father", "other's"), "おとう", "お父"),
        new DatabaseRecord("son", "むすこ", null),
        new DatabaseRecord("daughter", "むすめ", null),
        new DatabaseRecord(expl("wife", "informal"), "つま", "妻"),
        new DatabaseRecord(expl("wife", "formal"), "おくさん", "奥さん"),
        new DatabaseRecord(expl("husband","informal"), "おっと", "夫"),
        new DatabaseRecord(expl("husband","formal"), "ごしゅじん", "ご主人"),
        new DatabaseRecord(expl("family", "informal"), "かぞく", null),
        new DatabaseRecord(expl("family", "formal"), "ごかぞく", null),
        new DatabaseRecord("girlfriend", expl("かのじょ", "かぞく"), "彼女"),
        new DatabaseRecord("boyfriend", "かれし", null),
        new DatabaseRecord(expl("parents", "formal"), "ごりょうしん"),
        new DatabaseRecord(expl("parents", "informal"), "りょうしん", "両親"),
        new DatabaseRecord("parent", "おや", "親"),
        new DatabaseRecord("sibling", "きょうだい", null),
        new DatabaseRecord(expl("child", "other's"), "おこ", "子"),
        new DatabaseRecord(expl("child", "own"), "こども", "子供"),
        new DatabaseRecord("adult", "おとな"),
        new DatabaseRecord("brothers", expl("きょうだい", "兄弟"), "兄弟"),
        new DatabaseRecord("siblings", expl("きょうだい", "兄弟姉妹"), "兄弟"),
        new DatabaseRecord("sisters", "しまい", "姉妹"),
        new DatabaseRecord("relative", "しんせき", "親戚"),
        new DatabaseRecord("cousin", "いとこ"),
        new DatabaseRecord("uncle", "おじ"),
        new DatabaseRecord("aunt", "おば"),
        new DatabaseRecord("grandfather", "そふ", "祖父"),
        new DatabaseRecord("grandmother", "そぼ", "祖母"),
        new DatabaseRecord("grandchild", "まご", "孫"),
        new DatabaseRecord("granddaughter", "まごむすめ", "孫娘"),
        new DatabaseRecord("grandson", "まごむすこ", "孫息子"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> daytime() {
    return listOf(
        new DatabaseRecord("saturday", "どようび", "土曜日"),
        new DatabaseRecord("weekday", "へいじつ", "平日"),
        new DatabaseRecord("weekend", "しゅうまつ", "週末"),
        new DatabaseRecord("hour", "じ", null),
        new DatabaseRecord("half", "はん", "半"),
        new DatabaseRecord(expl("about", "time"), "ごろ", null),
        new DatabaseRecord("now", "いま", "今"),
        new DatabaseRecord("years old", "さい", "歳"),
        new DatabaseRecord("what time", "なんじ", null),
        new DatabaseRecord("often", "よく"),
        new DatabaseRecord("sometimes", "ときどき", "時々"),
        new DatabaseRecord("every", "まい", "舞"),

        new DatabaseRecord("day before yesterday", "おととい", "一昨日"),
        new DatabaseRecord("yesterday", "きのう", "昨日"),
        new DatabaseRecord("today", "きょう", "今日"),
        new DatabaseRecord("tomorrow", "あした", "明日"),
        new DatabaseRecord("day after tomorrow", "あさって", "明後日"),
        new DatabaseRecord("every day", "まいにち", "毎日"),


        new DatabaseRecord("this morning", "けさ", "今朝"),
        new DatabaseRecord("every morning", "まいあさ", "相朝"),
        new DatabaseRecord("last night", "ゆうべ", "夕べ"),
        new DatabaseRecord("this night", "こんばん", "今晩"),
        new DatabaseRecord("every night", "まいばん", "毎晩"),

        new DatabaseRecord("morning", "あさ", "朝"),
        new DatabaseRecord("daytime", "ひるま", "昼間"),
        new DatabaseRecord("noon", "ひる", "昼"),
        new DatabaseRecord("evening", "ゆうがた", "夕方"),
        new DatabaseRecord("night", "ばん", "晩"),
        new DatabaseRecord("midnight", "れいじ", "零時"),

        new DatabaseRecord("year", "とし", "年"),

        new DatabaseRecord("month", "つき", "月"),
        new DatabaseRecord("last month", "せんげつ", "先月"),
        new DatabaseRecord("this month", "こんげつ", "今月"),
        new DatabaseRecord("next month", "らいげつ", "来月"),


        new DatabaseRecord("week", "しゅう", "週"),
        new DatabaseRecord("every week", "まいしゅう", null),
        new DatabaseRecord("this week", "こんしゅう", "今週"),
        new DatabaseRecord("next week", "らいしゅう", "来週"),
        new DatabaseRecord("week after next", "さらいしゅう", "再来週"),


        new DatabaseRecord("always", "いつも", null),
        new DatabaseRecord("still", "まだ", null),
        new DatabaseRecord("minute", "ふん", "分"),
        new DatabaseRecord("perhaps", "たぶん", null),
        new DatabaseRecord("hours", "じかん", null),
        new DatabaseRecord(expl("about", "approximately"), "ぐらい", null),
        new DatabaseRecord("spring", "はる", null),
        new DatabaseRecord("day", "ひ", "日"),
        new DatabaseRecord("summer", "なつ", null),
        new DatabaseRecord("july", "しちがつ", null),
        new DatabaseRecord("september", "くがつ", null),
        new DatabaseRecord("fall", "あき", null),
        new DatabaseRecord("winter", "ふゆ", null),
        new DatabaseRecord("friday", "きんようび", "金曜日"),
        new DatabaseRecord("monday", "げつようび", "月曜日"),
        new DatabaseRecord("tuesday", "かようび", "火曜日"),
        new DatabaseRecord("wednesday", "すいようび", "水曜日"),
        new DatabaseRecord("what day", "なんようび", "何曜日"),
        new DatabaseRecord("thursday", "もくようび", "木曜日"),
        new DatabaseRecord("a.m.", "ごぜん"),
        new DatabaseRecord("p.m.", "ごご"),
        new DatabaseRecord("exactly", "ちょうど"),
        new DatabaseRecord("soon", "もうすぐ", null),
        new DatabaseRecord("immediately", "すぐ"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> color() {
    return listOf(
        new DatabaseRecordAdjectivePair("red", "あかい", Kanji.of("赤い")),
        new DatabaseRecordAdjectivePair("white", "しろい", Kanji.of("白い")),
        new DatabaseRecordAdjectivePair("purple", "むらさき", "の", Kanji.of("紫")),
        new DatabaseRecordAdjectivePair("blue", "あおい", Kanji.of("青い")),
        new DatabaseRecordAdjectivePair("black", "くろい", Kanji.of("黒い")),
        new DatabaseRecordAdjectivePair("green", "みどり", "の"),
        new DatabaseRecordAdjectivePair("orange", "オレンジいろ", "の"),
        new DatabaseRecordAdjectivePair("pink", "ピンクいろ", "の"),
        new DatabaseRecordAdjectivePair("yellow", "きいろい", Kanji.of("黄色い")),
        new DatabaseRecordAdjectivePair("brown", "ちゃいろ", "の", Kanji.of("茶色")),
//        new DatabaseRecordAdjectivePair("", "", "の"),
//        new DatabaseRecordAdjectivePair("", "", "の"),
//        new DatabaseRecordAdjectivePair("", "", "の"),
//        new DatabaseRecordAdjectivePair("", "", "の"),
//        new DatabaseRecordAdjectivePair("", "", "の"),
//        new DatabaseRecordAdjectivePair("", "", "の"),
//        new DatabaseRecordAdjectivePair("", "", "の"),
//        new DatabaseRecordAdjectivePair("", "", "の"),
        new DatabaseRecordAdjectivePair("", "")
    );
  }

  private List<DatabaseRecord> clothing() {
    return listOf(
        new DatabaseRecord("coat", "コート"),
        new DatabaseRecord("hat", "ぼうし", "帽子"),
        new DatabaseRecord("umbrella", "かさ", null),
        new DatabaseRecord("shoe", "くつ", "靴"),
        new DatabaseRecord("map", "ちず", "地図"),
        new DatabaseRecord("bag", "かばん", null),
        new DatabaseRecord("skirt", "スカート"),
        new DatabaseRecord("shirt", "シャツ"),
        new DatabaseRecord("wallet", "さいふ", null),
        new DatabaseRecord("clothes", "ふく", "服"),
        new DatabaseRecord("dress", "ドレス"),
        new DatabaseRecord("necktie", "ネクタイ"),
        new DatabaseRecord("pants", "ズボン"),
        new DatabaseRecord("underwear", "パンツ"),
        new DatabaseRecord("sweater", "セーター"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> place() {
    return listOf(
        new DatabaseRecord("hotel", "ホテル", null),
        new DatabaseRecord("bus stop", "バスてい", null),
        new DatabaseRecord("train station", "えき", "駅"),
        new DatabaseRecord("convenience store", "コンビニ", null),
        new DatabaseRecord("department store", "デパート", null),
        new DatabaseRecord("subway", "ちかてつ", "地下鉄"),
        new DatabaseRecord("airport", "くうこう", "空港"),
        new DatabaseRecord("town", "まち", null),
        new DatabaseRecord("city", "とし", "都市"),
        new DatabaseRecord("university", "だいがく", null),
        new DatabaseRecord("store", "みせ", null),
        new DatabaseRecord("restaurant", "レストラン", null),
        new DatabaseRecord("restroom", "おてあらい", null),
        new DatabaseRecord("final stop", "しゅうてん", null),
        new DatabaseRecord("park", "こうえん", "公園"),
        new DatabaseRecord("shrine", "じんじゃ", null),
        new DatabaseRecord("shop", "や", null),
        new DatabaseRecord("temple", "おてら", null),
        new DatabaseRecord("building", "たてもの", null),
        new DatabaseRecord("place", "ところ", null),
        new DatabaseRecord("plaza", "ひろば", null),
        new DatabaseRecord("zoo", "どうぶつえん", null),
        new DatabaseRecord("art museum", "びじゅつかん", null),
        new DatabaseRecord("hot spring", "おんせん", null),
        new DatabaseRecord("school", "がっこう", "学校"),
        new DatabaseRecord("home", "うち", null),
        new DatabaseRecord("castle", "しろ", null),
        new DatabaseRecord("garden", "にわ", "庭"),
        new DatabaseRecord("lobby", "ロビ-"),
        new DatabaseRecord("supermarket", "ス-パ-"),
        new DatabaseRecord("library", "としょかん"),
        new DatabaseRecord("company", "かいしゃ", "会社"),
        new DatabaseRecord("bar", "バ-"),
        new DatabaseRecord("cafeteria", "しょくどう", "食堂"),
        new DatabaseRecord("high school", "こうこう", "高校"),
        new DatabaseRecord("middle school", "ちゅうがく", "中学"),
        new DatabaseRecord("elementary school", "しょうがく", "小学"),
        new DatabaseRecord("corner", "かたすみ", "片隅"),
        new DatabaseRecord("movie theater", "えいがかん", "映画館"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> country() {
    return listOf(
        new DatabaseRecord("america", "アメリカ", null),
        new DatabaseRecord("canada", "カナダ", null),
        new DatabaseRecord("brazil", "ブラジル", null),
        new DatabaseRecord("britain", "イギリス", null),
        new DatabaseRecord("english", "えいご", null),
        new DatabaseRecord("japan", "にほん", "日本"),
        new DatabaseRecord("japanese", "にほんご", "日本ご"),
        new DatabaseRecord(expl("from", "place"), "しゅっしん", null),
        new DatabaseRecord("vietnam", "ベトナム", null),
        new DatabaseRecord("china", "ちゅうごく", null),
        new DatabaseRecord("chinese", "ちゅうごくご", null),
        new DatabaseRecord("korea", "かんこく", "韓国"),
        new DatabaseRecord("foreign language", "ごが", null),
        new DatabaseRecord("australia", "オーストラリア", null),
        new DatabaseRecord("france", "フランス", null),
        new DatabaseRecord("malaysia", "マレ-シア", null),
        new DatabaseRecord("seoul", "ソウル", null),
        new DatabaseRecord("taiwan", "たいわん", null),
        new DatabaseRecord("spain", "スペイン"),
        new DatabaseRecord("spanish", "スペインご"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> politeness() {
    return listOf(
        new DatabaseRecord("please", "ください", null),
        new DatabaseRecord("hello", "こんにちは", null),
        new DatabaseRecord("good evening", "こんばんは", null),
        new DatabaseRecord("see you tomorrow", "またあした", null),
        new DatabaseRecord("bye", "じゃね", null),
        new DatabaseRecord("excuse me", "すみません", null),
        new DatabaseRecord("good morning", "おはようございます", null),
        new DatabaseRecord("welcome", "ようこそ", null),
        new DatabaseRecord(expl("nice to meet you", "first time meeting"), "はじめまして", null),
        new DatabaseRecord(expl("nice to meet you", "treat me well"), "どうぞよろしく"),
        new DatabaseRecord("how much", "いくら", null),
        new DatabaseRecord("thank you", "ありがとうございます", null),
        new DatabaseRecord(expl("really", "is that so?"), "ほんとうですか", null),
        new DatabaseRecord("about how long", "どのぐらい", null),
        new DatabaseRecord("all right", "だいじょうぶ", null),
        new DatabaseRecord("how about", "どうですか", null),
        new DatabaseRecord("what is it", "なんですか", "何ですか"),
        new DatabaseRecord(expl("how old", "informal"), "なんさい", "何さい"),
        new DatabaseRecord(expl("how old", "formal"), "おいくつ"),
        new DatabaseRecord("that's right", "そうです"),
        new DatabaseRecord("that is not the case", "ちがいます", "違います"),
        new DatabaseRecord("how are you", "ちょうしはいかがですか", "調子はいかがですか"),
        new DatabaseRecord("a little bit", "ちょっとのあいだ", "ちょっとの間"),
        new DatabaseRecord("not sure", "さあ"),
        new DatabaseRecord("at all", "まったく"),
        new DatabaseRecord("not at all", "ぜんぜん", "全然"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> emotions() {
    return listOf(
        new DatabaseRecordAdjectivePair("nice", "やさしい"),
        new DatabaseRecordAdjectivePair("cool", "かっこいい"),
        new DatabaseRecordAdjectivePair("famous", "ゆうめい", "な"),
        new DatabaseRecordAdjectivePair("quiet", "しずか", "な"),
        new DatabaseRecordAdjectivePair("clean", "city", "きれい", "な", "とし"),
        new DatabaseRecordAdjectivePair("pretty", "flower", "きれい", "な", "はな"),
        new DatabaseRecordAdjectivePair("tasty", "おいしい"),
        new DatabaseRecordAdjectivePair("cheerful", "あかるい", Kanji.of("明るい")),
        new DatabaseRecordAdjectivePair("funny", "おもしろい"),
        new DatabaseRecordAdjectivePair("interesting", "class", "おもしろい", "じゅぎょう"),
        new DatabaseRecordAdjectivePair("lively", "にぎやか"),
        new DatabaseRecordAdjectivePair("big", "おおきい", Kanji.of("大きい")),
        new DatabaseRecordAdjectivePair("small", "ちいさい", Kanji.of("小さい")),
        new DatabaseRecordAdjectivePair("cute", "かわいい"),
        new DatabaseRecordAdjectivePair("busy", "いそがしい", Kanji.of("忙しい")),
        new DatabaseRecordAdjectivePair("smart", "あたまがいい"),
        new DatabaseRecordAdjectivePair("fashionable", "おしゃれ", "な"),
        new DatabaseRecordAdjectivePair("new", "あたらしい", Kanji.of("新しい")),
        new DatabaseRecordAdjectivePair("wanting", "ほしい", Kanji.of("欲しい")),
        new DatabaseRecordAdjectivePair("old", "ふるい", Kanji.of("古い")),
        new DatabaseRecordAdjectivePair("hideous", "ダサい"),
        new DatabaseRecordAdjectivePair("lovely", "すてき", "な"),
        new DatabaseRecordAdjectivePair("cheap", "やすい"),
        new DatabaseRecordAdjectivePair("expensive", "shoe", "たかい", "", "くつ", "高い"),
        new DatabaseRecordAdjectivePair("tall", "mountain", "たかい", "", "やま", "高い"),
//        new DatabaseRecordAdjectivePair(expl("nice", "a nice thing"), "いい"),
        new DatabaseRecordAdjectivePair("spacious", "ひろい"),
        new DatabaseRecordAdjectivePair("cramped", "せまい"),
        new DatabaseRecordAdjectivePair("well lit", "kitchen", "あかるい", "キッチン"),
        new DatabaseRecordAdjectivePair("fast", "はやい", Kanji.of("速い")),
        new DatabaseRecordAdjectivePair("bad", "わるい", Kanji.of("悪い")),
        new DatabaseRecordAdjectivePair("warm", "あたたかい"),
        new DatabaseRecordAdjectivePair("good health", "げんき", "な"),
        new DatabaseRecordAdjectivePair("dangerous", "あぶない", "な"),
        new DatabaseRecordAdjectivePair("hot", "あつい", Kanji.of("熱い")),
        new DatabaseRecordAdjectivePair("cold", "さむい"),
        new DatabaseRecordAdjectivePair("freezing", "つめたい", Kanji.of("冷たい")),
        new DatabaseRecordAdjectivePair("fun", "たのしい"),
        new DatabaseRecordAdjectivePair("hard", "たいへん", "な"),
        new DatabaseRecordAdjectivePair("various", "いろいろ", "な"),
        new DatabaseRecordAdjectivePair("sweet", "あまい", Kanji.of("甘い")),
        new DatabaseRecordAdjectivePair("short", "みじかい"),
        new DatabaseRecordAdjectivePair("convenient", "べんり", "な"),
        new DatabaseRecordAdjectivePair("salty", "しょっぱい"),
        new DatabaseRecordAdjectivePair("liked", "すき", "な"),
        new DatabaseRecordAdjectivePair("difficult", "むずかしい"),
        new DatabaseRecordAdjectivePair("scary", "こわい"),
        new DatabaseRecordAdjectivePair("boring", "つまらない"),
        new DatabaseRecordAdjectivePair("disliked", "きらい", "な", Kanji.of("嫌い")),
        new DatabaseRecordAdjectivePair("bad tasting", "tea", "まずい", "おちゃ"),
        new DatabaseRecordAdjectivePair("spicy", "からい"),
        new DatabaseRecordAdjectivePair("long", "ながい", Kanji.of("長い")),
        new DatabaseRecordAdjectivePair("low", "chair","ひくい", "", "いす", "低い"),
        new DatabaseRecordAdjectivePair("dirty", "きたない"),
        new DatabaseRecordAdjectivePair("slow", "おそい", Kanji.of("遅い")),
        new DatabaseRecordAdjectivePair("close", "ちかい", Kanji.of("近い")),
        new DatabaseRecordAdjectivePair("far", "とおい", Kanji.of("遠い")),

        new DatabaseRecordAdjectivePair("strong", "つよい", Kanji.of("強い")),
        new DatabaseRecordAdjectivePair("weak", "よわい", Kanji.of("弱い")),
        new DatabaseRecordAdjectivePair("dark", "weather","くらい", "", "てんき", "暗い"),
        new DatabaseRecordAdjectivePair("bright", "weather", "あかるい", "", "てんき", "明るい"),
        new DatabaseRecordAdjectivePair("many", "おおい", Kanji.of("多い")),
//        new DatabaseRecordAdjectivePair("", ""),
//        new DatabaseRecordAdjectivePair("", ""),
//        new DatabaseRecordAdjectivePair("", ""),
//        new DatabaseRecordAdjectivePair("", ""),
        new DatabaseRecordAdjectivePair("", "")
    );
  }

  private List<DatabaseRecord> jobs() {
    return listOf(
        new DatabaseRecord("doctor", "いしゃ", null),
        new DatabaseRecord("teacher", "せんせい", null),
        new DatabaseRecord("lawyer", "べんごし", null),
        new DatabaseRecord("student", "がくせい", null),
        new DatabaseRecord("person", "ひと", "人"),
        new DatabaseRecord("nurse", "かんごし", null),
        new DatabaseRecord("engineer", "エンジニア", null),
        new DatabaseRecord("office worker", "かいしゃいん", null),
        new DatabaseRecord("warrior", "ぶし", null),
        new DatabaseRecord("photographer", "しゃしんか", null),
        new DatabaseRecord("driver", "うんてんしゅ"),
        new DatabaseRecord("translator", "ほんやくか"),
        new DatabaseRecord("coach", "コ-チ", null),
        new DatabaseRecord("manager", "マネージャー"),
        new DatabaseRecord("coworker", "どうりょう"),
        new DatabaseRecord("actor", "はいゆう"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> foods() {
    return listOf(
        new DatabaseRecord("sushi", "すし", null),
        new DatabaseRecord("green tea", "おちゃ", null),
        new DatabaseRecord("rice", "ごはん", null),
        new DatabaseRecord("water", "みず", "水"),
        new DatabaseRecord("curry", "カレー", null),
        new DatabaseRecord("ramen", "ラーメン", null),
        new DatabaseRecord("pizza", "ピザ", null),
        new DatabaseRecord("cake", "ケーキ", null),
        new DatabaseRecord("coffee", "コーヒー", null),
        new DatabaseRecord("vegetable", "やさい", "野菜"),
        new DatabaseRecord("bread", "パン", null),
        new DatabaseRecord("sandwich", "サンドイッチ", null),
        new DatabaseRecord("breakfast", "あさごはん", "朝ご飯"),
        new DatabaseRecord("lunch", "ひるごはん", "昼ご飯"),
        new DatabaseRecord("boxed lunch", "べんとう", "弁当"),
        new DatabaseRecord("dinner", "ばんごはん", "晩ご飯"),
        new DatabaseRecord("udon", "うどん", null),
        new DatabaseRecord("miso soup", "みそしる", null),
        new DatabaseRecord("soba", "そば", null),
        new DatabaseRecord("iced coffee", "アイスコーヒー", null),
        new DatabaseRecord("black tea", "こうちゃ", null),
        new DatabaseRecord("ice cream", "アイスクリーム", null),
        new DatabaseRecord("salad", "サラダ", null),
        new DatabaseRecord("rice ball", "おにぎり", null),
        new DatabaseRecord("meal set", "ていしょく", null),
        new DatabaseRecord("tempura", "てんぷら", null),
        new DatabaseRecord("pasta", "パスタ", null),
        new DatabaseRecord("souvenir", "おみやげ", "お土産"),
        new DatabaseRecord("snack", "おかし", null),
        new DatabaseRecord("dessert", "デザ-ト", null),
        new DatabaseRecord("meat", "にく", "肉"),
        new DatabaseRecord("cocoa", "ココア", null),
        new DatabaseRecord("pie", "パイ"),
        new DatabaseRecord("donut", "ド-ナツ"),
        new DatabaseRecord("chocolate", "チョコレ-ト"),
        new DatabaseRecord("mint chocolate chip", "チョコミント"),
        new DatabaseRecord("cookie", "クッキ-"),
        new DatabaseRecord("strawberry", "いちご"),
        new DatabaseRecord("matcha", "まっちゃ"),
        new DatabaseRecord("cupcake", "カップケ-キ"),
        new DatabaseRecord("cheesecake", "チ-ズケ-キ"),
        new DatabaseRecord("miso pork cutlet", "みそかつ"),
        new DatabaseRecord("soy sauce", "しょうゆ"),
        new DatabaseRecord("pork", "ぶたにく"),
        new DatabaseRecord("cola", "コ-ラ"),
        new DatabaseRecord("beer", "ビ-ル"),
        new DatabaseRecord("raw", "なま"),
        new DatabaseRecord("sauce", "ソ-ス"),
        new DatabaseRecord("pork cutlet", "とんかつ"),
        new DatabaseRecord("salt", "しお"),
        new DatabaseRecord("beef bowl", "ぎゅうどん"),
        new DatabaseRecord("tofu", "とうふ"),
        new DatabaseRecord("egg", "たまご"),
        new DatabaseRecord("vanilla", "バニラ"),
        new DatabaseRecord("french　fries", "フライドポテト"),
        new DatabaseRecord("fried rice", "チャ-ハン"),
        new DatabaseRecord("milk", "ぎゅうにゅう", "牛乳"),
        new DatabaseRecord("apple", "りんご"),
        new DatabaseRecord("steak", "ステーキ"),
        new DatabaseRecord("menu", "メニュー"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> numbers() {
    return listOf(
        new DatabaseRecord("one", "いち", "一"),
        new DatabaseRecord("two", "に", "二"),
        new DatabaseRecord("three", "さん", "三"),
        new DatabaseRecord("four", "よん", "四"),
        new DatabaseRecord("five", "ご", "五"),
        new DatabaseRecord("six", "ろく", "六"),
        new DatabaseRecord("seven", "なな", "七"),
        new DatabaseRecord("eight", "はち", "八"),
        new DatabaseRecord("nine", "きゅう", "九"),
        new DatabaseRecord("ten", "じゅう", "十"),
        new DatabaseRecord("hundred", "ひゃく", "百"),
        new DatabaseRecord("yen", "えん", "円"),
        new DatabaseRecord("thousand", "せん", "千"),
        new DatabaseRecord("ten thousand", "まん", "万"),
        new DatabaseRecord("zero", "ゼロ", "〇"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> animals() {
    return listOf(
        new DatabaseRecord("dog", "いぬ", "犬"),
        new DatabaseRecord("puppy", "こいぬ", "子犬"),
        new DatabaseRecord("cat", "ねこ", "猫"),
        new DatabaseRecord("kitten", "こねこ", "子猫"),
        new DatabaseRecord("lion", "ライオン", null),
        new DatabaseRecord("pig", "ぶた"),
        new DatabaseRecord("fish", "さかな", "魚"),
        new DatabaseRecord("bird", "とり", "鳥"),
        new DatabaseRecord("pet", "ペット"),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> alignment() {
    return listOf(
        new DatabaseRecord("left", "ひだり", "左"),
        new DatabaseRecord("right", "みぎ", "右"),
        new DatabaseRecord("above", "うえ", "上"),
        new DatabaseRecord("below", "した", "下"),
        new DatabaseRecord("before", "まえ", "前"),
        new DatabaseRecord("behind", "うしろ", "後ろ"),
        new DatabaseRecord("beside", "よこ", "横"),
        new DatabaseRecord("between", "あいだ", "間"),
        new DatabaseRecord("next door", "となり", "隣"),
        new DatabaseRecord("inside", "なか", "中"),
        new DatabaseRecord("outside", "そと", "外"),
        new DatabaseRecord("", "", ""),
        new DatabaseRecord("", "", ""),
        new DatabaseRecord("", "", ""),
        new DatabaseRecord("", "", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> xxx() {
    return listOf(
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""),
        new DatabaseRecord("", ""));
  }

  private List<DatabaseRecord> listOf(DatabaseRecord... databaseRecords) {
    List<DatabaseRecord> recs = new ArrayList<>();

    for (DatabaseRecord r : databaseRecords) {
      if ("".equals(r.getEnglish()) && "".equals(r.getJapanese())) {
        continue;
      }
      if ("".equals(r.getEnglish()) || "".equals(r.getJapanese())) {
        throw new IllegalStateException("Found missing english or japanese: " + r.getEnglish() + " / " + r.getJapanese());
      }
      recs.add(r);
    }

    return recs;
  }

  private List<DatabaseRecord> listOf(DatabaseRecordAdjectivePair... databaseRecords) {
    List<DatabaseRecord> recs = new ArrayList<>();

    for (DatabaseRecordAdjectivePair r : databaseRecords) {
      if ("".equals(r.getEnglishMain()) && "".equals(r.getJapaneseMain())) {
        continue;
      }
      if ("".equals(r.getEnglishMain()) || "".equals(r.getJapaneseMain())) {
        throw new IllegalStateException("Found missing english or japanese: " + r.getEnglishMain() + " / " + r.getJapaneseMain());
      }
      recs.add(new DatabaseRecord(expl(r.getEnglishMain(), r.getEnglishSubject()), r.getJapaneseMain(), r.getKanji()));
      recs.add(new DatabaseRecAdj(r.getEnglishMain() + " " + r.getEnglishSubject(), r.getJapaneseMain() + r.getJapaneseConnector() + r.getJapaneseSubject()));
    }

    return recs;
  }

  private Explanation expl(String value, String explanation) {
    return new Explanation(value, explanation);
  }

  @Getter
  @AllArgsConstructor(staticName = "of")
  static class Kanji {
    private final String kanji;
  }
}
